#version 450 core

#define THREAD_SIZE 1


// Input size.
layout (set = 2, binding = 0) uniform DataSize
{
    int dataSizeInputBytes;
};

// Atomic value buffer
layout (set = 1, binding = 0) restrict buffer DataOut4
{
    ivec4 atomicValues[];
};


layout (local_size_x = THREAD_SIZE, local_size_y = 1, local_size_z = 1) in;
void main()
{
    for(int i = 0; i < 2; ++i)
    {
        atomicValues[i] = ivec4(0);
    }
}

